language: node_js
node_js:
  - "8.11"

branches:
  only:
    - master

addons:
    chrome: stable

cache:
    directories:
        - node_modules

script: 
- npm test
- npm start

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master